### ISSUE TITLE
 Cannot find module 'vue-template-compiler/package.json'

### ISSUE THREAD

**Issue by adnanaz** [matt-auckland/vite-vue2-starter#3]
Since rc.11 we make vue-template-compiler a peer dependency of @vue/cli-service, so installing @vue/cli-service-global won't automatically install vue-template-compiler.

A temporary workaround is to manually run npm i -g vue-template-compiler

source : https://github.com/vuejs/vue-cli/issues/2109

**Comment by matt-auckland** [comment]
I will update the template sometime soon to fix this, thanks for raising

**Comment by adnanaz** [comment]
the solutions is just need to add package, run npm i -g vue-template-compiler and your template error goona fix.
