### ISSUE TITLE
Article: missing `{{count}}` in `HelloWorld.vue`

### ISSUE THREAD

**Issue by chriscalo** [matt-auckland/vite-vue2-starter#5]
<img width="731" alt="Screenshot 2022-02-17 at 21 43 52" src="https://user-images.githubusercontent.com/867717/154607704-4f11c1f3-79cf-4044-9a89-7fed603c893c.png">

In [your article](https://www.mathew-paul.nz/posts/how-to-use-vue2-with-vite/), the code for `HelloWorld.vue` is rendered incorrectly. There's a line that reads:

```vue
<button @click="count++">count is: </button>
```

when it should be:

```vue
<button @click="count++">count is: {{count}}</button>
```

I imagine the double curlies are getting swallowed by whatever is processing that code block and they need to be escaped.

**Comment by matt-auckland** [comment]
Good catch, thanks for that. Will fix this soon
